/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_perfmsr_core_PerformanceMonitor */

#ifndef _Included_org_eclipse_perfmsr_core_PerformanceMonitor
#define _Included_org_eclipse_perfmsr_core_PerformanceMonitor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _debug */
/* Inaccessible static: _isLoaded */
#undef org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_ELASPED_IDX
#define org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_ELASPED_IDX 2L
#undef org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_USER_TIME_IDX
#define org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_USER_TIME_IDX 3L
#undef org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_KERNEL_TIME_IDX
#define org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_KERNEL_TIME_IDX 4L
#undef org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_COMMITTED_IDX
#define org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_COMMITTED_IDX 6L
#undef org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_OPEN_HANDLES_IDX
#define org_eclipse_perfmsr_core_PerformanceMonitor_WHAT_OPEN_HANDLES_IDX 9L
/* Inaccessible static: _df */
/* Inaccessible static: _map */
/*
 * Class:     org_eclipse_perfmsr_core_PerformanceMonitor
 * Method:    nativeGetPerformanceInfo
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_perfmsr_core_PerformanceMonitor_nativeGetPerformanceInfo
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     org_eclipse_perfmsr_core_PerformanceMonitor
 * Method:    nativeGetPerformanceCounters
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_perfmsr_core_PerformanceMonitor_nativeGetPerformanceCounters
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     org_eclipse_perfmsr_core_PerformanceMonitor
 * Method:    nativeGetUUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_perfmsr_core_PerformanceMonitor_nativeGetUUID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
