/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 137,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1224,

					NT_OFFSET = 137,
					SCOPE_UBOUND = 322,
					SCOPE_SIZE = 323,
					LA_STATE_OFFSET = 18221,
					MAX_LA = 1,
					NUM_RULES = 940,
					NUM_TERMINALS = 137,
					NUM_NON_TERMINALS = 433,
					NUM_SYMBOLS = 570,
					START_STATE = 984,
					EOFT_SYMBOL = 64,
					EOLT_SYMBOL = 64,
					ACCEPT_ACTION = 18220,
					ERROR_ACTION = 18221;
}
