/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 140,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1262,

					NT_OFFSET = 140,
					SCOPE_UBOUND = 321,
					SCOPE_SIZE = 322,
					LA_STATE_OFFSET = 18370,
					MAX_LA = 1,
					NUM_RULES = 956,
					NUM_TERMINALS = 140,
					NUM_NON_TERMINALS = 440,
					NUM_SYMBOLS = 580,
					START_STATE = 1508,
					EOFT_SYMBOL = 38,
					EOLT_SYMBOL = 38,
					ACCEPT_ACTION = 18369,
					ERROR_ACTION = 18370;
}
