/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 135,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1205,

					NT_OFFSET = 135,
					SCOPE_UBOUND = 313,
					SCOPE_SIZE = 314,
					LA_STATE_OFFSET = 17578,
					MAX_LA = 1,
					NUM_RULES = 918,
					NUM_TERMINALS = 135,
					NUM_NON_TERMINALS = 423,
					NUM_SYMBOLS = 558,
					START_STATE = 991,
					EOFT_SYMBOL = 64,
					EOLT_SYMBOL = 64,
					ACCEPT_ACTION = 17577,
					ERROR_ACTION = 17578;
}
